// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/Dahasolo/urlshortener/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// URLRepository is an autogenerated mock type for the URLRepository type
type URLRepository struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *URLRepository) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *URLRepository) Get(ctx context.Context, id string) (service.ResolveResult, bool) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 service.ResolveResult
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) (service.ResolveResult, bool)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) service.ResolveResult); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(service.ResolveResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetExistingID provides a mock function with given fields: ctx, url, userID
func (_m *URLRepository) GetExistingID(ctx context.Context, url string, userID string) (string, bool) {
	ret := _m.Called(ctx, url, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetExistingID")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, bool)); ok {
		return rf(ctx, url, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, url, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = rf(ctx, url, userID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetUserURLs provides a mock function with given fields: ctx, userID
func (_m *URLRepository) GetUserURLs(ctx context.Context, userID string) ([]service.URLRecord, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserURLs")
	}

	var r0 []service.URLRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]service.URLRecord, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []service.URLRecord); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.URLRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAsDeleted provides a mock function with given fields: ctx, ids, userID
func (_m *URLRepository) MarkAsDeleted(ctx context.Context, ids []string, userID string) error {
	ret := _m.Called(ctx, ids, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsDeleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) error); ok {
		r0 = rf(ctx, ids, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Ping provides a mock function with given fields: ctx
func (_m *URLRepository) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, id, url, userID
func (_m *URLRepository) Save(ctx context.Context, id string, url string, userID string) error {
	ret := _m.Called(ctx, id, url, userID)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, id, url, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveMany provides a mock function with given fields: ctx, entries, userID
func (_m *URLRepository) SaveMany(ctx context.Context, entries []service.BatchEntry, userID string) error {
	ret := _m.Called(ctx, entries, userID)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []service.BatchEntry, string) error); ok {
		r0 = rf(ctx, entries, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewURLRepository creates a new instance of URLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLRepository {
	mock := &URLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
