// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	service "github.com/Dahasolo/urlshortener/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// URLRepository is an autogenerated mock type for the URLRepository type
type URLRepository struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *URLRepository) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *URLRepository) Get(id string) (string, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetExistingID provides a mock function with given fields: url, userID
func (_m *URLRepository) GetExistingID(url string, userID string) (string, bool) {
	ret := _m.Called(url, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetExistingID")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string, string) (string, bool)); ok {
		return rf(url, userID)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(url, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) bool); ok {
		r1 = rf(url, userID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetUserURLs provides a mock function with given fields: userID
func (_m *URLRepository) GetUserURLs(userID string) ([]service.URLRecord, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserURLs")
	}

	var r0 []service.URLRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]service.URLRecord, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []service.URLRecord); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.URLRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with no fields
func (_m *URLRepository) Ping() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: id, url, userID
func (_m *URLRepository) Save(id string, url string, userID string) error {
	ret := _m.Called(id, url, userID)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(id, url, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveMany provides a mock function with given fields: entries, userID
func (_m *URLRepository) SaveMany(entries []service.BatchEntry, userID string) error {
	ret := _m.Called(entries, userID)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]service.BatchEntry, string) error); ok {
		r0 = rf(entries, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewURLRepository creates a new instance of URLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLRepository {
	mock := &URLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
